[versions]

# general
lombok = "1.18.42"
jetbrains-annotations = "26.0.2"
junit-jupiter = "5.12.2"
junit-platform = "1.12.2"

# adventure
adventure = "4.17.0"
adventure-minimessage = "4.17.0"
adventure-gson = "4.17.0"
adventure-legacy = "4.17.0"
adventure-plain = "4.17.0"

[libraries]

# general
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }

# adventure
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure-minimessage" }
adventure-gson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure-gson" }
adventure-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure-legacy" }
adventure-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure-plain" }
