[versions]

# general
lombok = "1.18.42"
jetbrains-annotations = "26.0.2"

# adventure
adventure = "4.17.0"

[libraries]

# general
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }

# adventure
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
