name: Publish Development Build

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute VERSION
        run: echo "VERSION=${GITHUB_REF##*/}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Publish all modules to repository
        env:
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          VERSION: ${{ env.VERSION }}
          PUBLISH_REALM: development
        run: ./gradlew --no-daemon publish


